### ISSUE TITLE
Refresh token got 500 internal error after hit double

### ISSUE THREAD

**Issue by Mcx002** [septemberkid/service-with-express#3]
![image](https://github.com/septemberkid/service-with-express/assets/68631992/b81996e6-81a6-4bd4-96f3-a727da5bdafa)

preview response
```
{
  "message": "insert into \"public\".\"app_refresh_token\" (\"id\", \"user_id\", \"expired_at\") values ('1b07cafd-f1e2-5b05-81d8-fcb43bccc7a0', 2, '2023-06-21 05:25:06') returning \"id\" - duplicate key value violates unique constraint \"app_refresh_token_pkey\"",
  "result": null,
  "meta": null
}
```

![image](https://github.com/septemberkid/service-with-express/assets/68631992/a80e7d2e-ca53-4c61-8927-763f28d3586e)

refresh token better as the same format with access token which means jwt. so the one and another will be different and not the same. and after refresh token, the given back refresh token should be changed too

**Comment by septemberkid** [comment]
ketika hit endpoint refresh token, akan mengembalikan refresh token baru, jadi harus diupdate dlu.
Refresh token pasti unique walaupun dalam format UUID karena udah diconcat dengan timestamp

**Comment by Mcx002** [comment]
hmm kesalahan disaya sepertinya karena nge load refresh token 1 dengan yang lain kecepetan.
paling kalo gitu access tokennya perlu dibalikin expiredAt nya, karena fe nggk tau kapan si jwtnya expired gk tau juga refreshnya kapan

**Comment by septemberkid** [comment]
jwt expired udah ada di dipayload, utk refresh token lifetimenya 1 blan.
Perubahannya ak commit, issue ini akan diclose
